---
# Woodpecker CI Pipeline for Codeberg
# Tests infrastructure code on every push

when:
  - event: push
    branch: main
  - event: pull_request

steps:
  # ========================================
  # Step 1: Terraform Format Check
  # ========================================
  terraform-fmt:
    image: hashicorp/terraform:1.6
    commands:
      - cd terraform
      - terraform fmt -check -recursive
    when:
      - event: push
      - event: pull_request

  # ========================================
  # Step 2: Terraform Lint (tflint)
  # ========================================
  terraform-lint:
    image: ghcr.io/terraform-linters/tflint:latest
    commands:
      - cd terraform
      - tflint --init
      - tflint --format compact
    when:
      - event: push
      - event: pull_request

  # ========================================
  # Step 3: Terraform Validate
  # ========================================
  terraform-validate:
    image: hashicorp/terraform:1.6
    commands:
      - cd terraform
      - terraform init -backend=false
      - terraform validate
    when:
      - event: push
      - event: pull_request

  # ========================================
  # Step 4: Terraform Test (Terratest)
  # ========================================
  terraform-test:
    image: golang:1.21-alpine
    secrets:
      - hcloud_token
    environment:
      GO111MODULE: "on"
    commands:
      - apk add --no-cache git
      - cd terraform/tests
      - go mod download
      - go test -v -timeout 30m -short
    when:
      - event: push
        branch: main

  # ========================================
  # Step 5: Ansible Syntax Check
  # ========================================
  ansible-syntax:
    image: cytopia/ansible:latest-tools
    commands:
      - cd ansible
      - ansible-playbook playbooks/site.yml --syntax-check
    when:
      - event: push
      - event: pull_request

  # ========================================
  # Step 6: Ansible Lint
  # ========================================
  ansible-lint:
    image: cytopia/ansible:latest-tools
    commands:
      - cd ansible
      - ansible-lint --force-color playbooks/site.yml
    when:
      - event: push
      - event: pull_request

  # ========================================
  # Step 7: YAML Lint
  # ========================================
  yaml-lint:
    image: cytopia/yamllint:latest
    commands:
      - yamllint -c .yamllint.yml ansible/ || true
      - yamllint -c .yamllint.yml .woodpecker/ || true
    when:
      - event: push
      - event: pull_request

  # ========================================
  # Step 8: Molecule Tests (Ansible Roles)
  # ========================================
  molecule-test:
    image: quay.io/ansible/molecule:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - cd ansible/roles
      - |
        for role in */; do
          if [ -d "$role/molecule" ]; then
            echo "Testing role: $role"
            cd "$role"
            molecule test --all || exit 1
            cd ..
          fi
        done
    when:
      - event: push
        branch: main
      - event: pull_request

  # ========================================
  # Step 6: Notify on Success
  # ========================================
  notify-success:
    image: alpine:latest
    commands:
      - echo "✅ All tests passed!"
    when:
      - event: push
      - event: pull_request
      - status: success

  # ========================================
  # Step 7: Notify on Failure
  # ========================================
  notify-failure:
    image: alpine:latest
    commands:
      - echo "❌ Tests failed!"
      - exit 1
    when:
      - event: push
      - event: pull_request
      - status: failure
