# Generated by Terraform - DO NOT EDIT MANUALLY
# Run: tofu output -json > ../../../ansible/inventory/terraform-output.json

all:
  children:
    hetzner:
      hosts:
%{ for env, servers in servers ~}
%{ for hostname, config in servers.hosts ~}
        ${hostname}:
          ansible_host: ${config.ansible_host}
          ansible_user: ${config.ansible_user}
          ansible_ssh_private_key_file: ${config.ansible_ssh_private_key_file}
          server_id: ${config.server_id}
          server_type: ${config.server_type}
          location: ${config.location}
          environment: ${config.environment}
%{ endfor ~}
%{ endfor ~}
