# ============================================================
# AUTO-GENERATED BY TERRAFORM - DO NOT EDIT MANUALLY
# ============================================================
# This file is regenerated on every terraform apply
# To modify, edit terraform/templates/ssh_config.tpl
# ============================================================

Host ${hostname}
    HostName ${host_address}
    User ${user}
    IdentityFile ${ssh_key}
    IdentitiesOnly yes
    StrictHostKeyChecking ask
    UserKnownHostsFile ~/.ssh/known_hosts
    
    # Yubikey FIDO2
    SecurityKeyProvider internal
    
    # Connection settings
    ServerAliveInterval 60
    ServerAliveCountMax 3
    TCPKeepAlive yes
    
    # Compression
    Compression yes
    
    # Forward agent (disable for security)
    ForwardAgent no
    ForwardX11 no
